menu:
  ä¸»é¡µ: /
  å½’æ¡£: /archives

logo: 'Â¯\_(ãƒ„)_/Â¯'

more:
  my photos: https://gallery.gaoryrt.com/
  About Me: /about.html
  GitHub: https://github.com/gaoryrt/
  å¾®åš: http://weibo.com/R1T1AN
  rss: /rss2.xml
  å‹é“¾: /links.html

about:
  title: Guestbook
  link: https://frankenstein-ashen.now.sh/

show_toc_bool: false

excerpt_num: 150

footer_info: Â© gaoryrt 2015-202ğŸ¯
